codecov:
  notify:
    require_ci_to_pass: true
comment: off
coverage:
  precision: 2
  range:
  - 50.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
ignore:
    - "specs"
    - "minion/ovsdb/ovsdb_mock.go"
    - "cluster/digitalocean/mock_client.go"
